_wandb:
    value:
        cli_version: 0.19.9
        code_path: code/examples/finetune_rgb.py
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 2
                - 3
                - 12
                - 45
                - 49
                - 55
            "2":
                - 2
                - 3
                - 11
                - 12
                - 45
                - 49
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
